urls.py
# urls.py
from django.conf.urls import url, include
from otree.urls import urlpatterns

urlpatterns.append(
    url(r'^ajax_chat/', include('chat.ajax', namespace="ajax_chat"))
)

toilet_questionnaire_3/models.py
# -*- coding: utf-8 -*-
# <standard imports>
from __future__ import division

import random

import otree.models
from otree.db import models
from otree import widgets
from otree.common import Currency as c, currency_range, safe_json
from otree.constants import BaseConstants
from otree.models import BaseSubsession, BaseGroup, BasePlayer

# </standard imports>

author = 'Your name here'

doc = """
Your app description
"""


class Constants(BaseConstants):
    name_in_url = 'toilet_questionnaire_3'
    players_per_group = None
    num_rounds = 1


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    q3_second_game_results_surprised = models.PositiveIntegerField(min=1, max=10,
                                                                   widget=widgets.SliderInput(show_value=False))
    q3_second_game_results_satisfied = models.PositiveIntegerField(min=1, max=10,
                                                                   widget=widgets.SliderInput(show_value=False))
    q3_second_game_results_upset = models.PositiveIntegerField(min=1, max=10,
                                                               widget=widgets.SliderInput(show_value=False))

    q3_second_game_teamwork = models.PositiveIntegerField(min=1, max=10, widget=widgets.SliderInput(show_value=False))
    q3_second_game_teamspirit = models.PositiveIntegerField(min=1, max=10, widget=widgets.SliderInput(show_value=False))
    q3_communication_inputs_maxresources_how_useful = models.PositiveIntegerField(min=1, max=10,
                                                                                  widget=widgets.SliderInput(
                                                                                      show_value=False))
    q3_followed_communication_inputs = models.PositiveIntegerField(min=1, max=10,
                                                                   widget=widgets.SliderInput(show_value=False))
    q3_took_advantage_communication_inputs = models.PositiveIntegerField(min=1, max=10,
                                                                         widget=widgets.SliderInput(show_value=False))
    q3_majority_followed_communication_inputs = models.PositiveIntegerField(min=1, max=10, widget=widgets.SliderInput(
        show_value=False))
    q3_majority_took_advantage_communication_inputs = models.PositiveIntegerField(min=1, max=10,
                                                                                  widget=widgets.SliderInput(
                                                                                      show_value=False))
    q3_minority_followed_communication_inputs = models.PositiveIntegerField(min=1, max=10, widget=widgets.SliderInput(
        show_value=False))
    q3_minority_took_advantage_communication_inputs = models.PositiveIntegerField(min=1, max=10,
                                                                                  widget=widgets.SliderInput(
                                                                                      show_value=False))
    q3_how_max_resources_communication_inputs_if_followed = models.PositiveIntegerField(min=1, max=10,
                                                                                        widget=widgets.SliderInput(
                                                                                            show_value=False))
    q3_after_second_round_like_others = models.PositiveIntegerField(min=1, max=10,
                                                                    widget=widgets.SliderInput(show_value=False))
    q3_second_round_impressions = models.TextField()
    q3_best_strategy_to_max_resources = models.TextField()
    q3_gender = models.CharField(choices=["M", "F"], widget=widgets.RadioSelectHorizontal())
    q3_birthday = models.CharField(max_length=4, default='XXXX')  #  q3_birthday = models.DateField(widget=widgets.Input()
    q3_main_subject_in_university = models.TextField()
    q3_already_take_part_in_a_problem_solving = models.CharField(max_length=255, widget=widgets.RadioSelect(),
                                                                 choices=['Ja', 'Nein'])
    q3_already_took_part_x_times_for_x_months = models.TextField(default='X Male und das letzte Mal vor X Monaten.')
    q3_experiment_itself_was_interessting = models.PositiveIntegerField(min=1, max=10,
                                                                        widget=widgets.SliderInput(show_value=False))
    q3_were_you_personally_engaged_achieving_good_results = models.PositiveIntegerField(min=1, max=10,
                                                                                        widget=widgets.SliderInput(
                                                                                            show_value=False))
    q3_dificult_understanding_and_solving_the_problem = models.PositiveIntegerField(min=1, max=10,
                                                                                    widget=widgets.SliderInput(
                                                                                        show_value=False))
    q3_was_it_obvious_what_to_do = models.PositiveIntegerField(min=1, max=10,
                                                               widget=widgets.SliderInput(show_value=False))
    q3_count_unclear_questions = models.TextField()
    q3_unclear_questions_description = models.TextField()
    q3_technical_issues = models.CharField(max_length=255, widget=widgets.RadioSelect(), choices=['Ja', 'Nein'])
    q3_technical_issues_details = models.TextField()
    q3_opinion_about_questions_and_hypotheses = models.TextField()

    # confidant

    q3_confidant_second_game_teamwork = models.PositiveIntegerField(min=1, max=10,
                                                                    widget=widgets.SliderInput(show_value=False))
    q3_confidant_second_game_teamspirit = models.PositiveIntegerField(min=1, max=10,
                                                                      widget=widgets.SliderInput(show_value=False))
    q3_confidant_majority_followed_communication_inputs = models.PositiveIntegerField(min=1, max=10,
                                                                                      widget=widgets.SliderInput(
                                                                                          show_value=False))
    q3_confidant_majority_took_advantage_communication_inputs = models.PositiveIntegerField(min=1, max=10,
                                                                                            widget=widgets.SliderInput(
                                                                                                show_value=False))
    q3_confidant_minority_followed_communication_inputs = models.PositiveIntegerField(min=1, max=10,
                                                                                      widget=widgets.SliderInput(
                                                                                          show_value=False))
    q3_confidant_minority_took_advantage_communication_inputs = models.PositiveIntegerField(min=1, max=10,
                                                                                            widget=widgets.SliderInput(
                                                                                                show_value=False))
    q3_confidant_best_strategy_to_max_resources = models.TextField()
    q3_confidant_gender = models.CharField(choices=["M", "F"], widget=widgets.RadioSelectHorizontal())
    q3_confidant_birthday = models.TextField(default='Jahrgang') #  q3_confidant_birthday = models.DateField(widget=widgets.Input())
    q3_confidant_main_subject_in_university = models.TextField()
    q3_confidant_already_take_part_in_a_problem_solving = models.CharField(max_length=255, widget=widgets.RadioSelect(),
                                                                           choices=['Ja', 'Nein'])
    q3_confidant_already_took_part_x_times_for_x_months = models.TextField(
        default='X Male und das letzte Mal vor X Monaten.')
    q3_confidant_experiment_itself_was_interessting = models.PositiveIntegerField(min=1, max=10,
                                                                                  widget=widgets.SliderInput(
                                                                                      show_value=False))
    q3_confidant_were_you_personally_engaged_achieving_good_results = models.PositiveIntegerField(min=1, max=10,
                                                                                                  widget=widgets.SliderInput(
                                                                                                      show_value=False))
    q3_confidant_dificult_understanding_and_solving_the_problem = models.PositiveIntegerField(min=1, max=10,
                                                                                              widget=widgets.SliderInput(
                                                                                                  show_value=False))
    q3_confidant_was_it_obvious_what_to_do = models.PositiveIntegerField(min=1, max=10,
                                                                         widget=widgets.SliderInput(show_value=False))
    q3_confidant_count_unclear_questions = models.TextField()
    q3_confidant_unclear_questions_description = models.TextField()
    q3_confidant_technical_issues = models.CharField(max_length=255, widget=widgets.RadioSelect(),
                                                     choices=['Ja', 'Nein'])
    q3_confidant_technical_issues_details = models.TextField()


toilet_questionnaire_3/views.py
# -*- coding: utf-8 -*-
from __future__ import division

from otree.common import Currency as c, currency_range, safe_json

from . import models
from ._builtin import Page, WaitPage
from .models import Constants


class ConfidantQ3(Page):
    form_model = models.Player
    form_fields = [

        'q3_confidant_second_game_teamwork',
        'q3_confidant_second_game_teamspirit',
        'q3_confidant_majority_followed_communication_inputs',
        'q3_confidant_majority_took_advantage_communication_inputs',
        'q3_confidant_minority_followed_communication_inputs',
        'q3_confidant_minority_took_advantage_communication_inputs',
        'q3_confidant_best_strategy_to_max_resources',
        'q3_confidant_gender',
        'q3_confidant_birthday',
        'q3_confidant_main_subject_in_university',
        'q3_confidant_already_take_part_in_a_problem_solving',
        'q3_confidant_already_took_part_x_times_for_x_months',
        'q3_confidant_experiment_itself_was_interessting',
        'q3_confidant_were_you_personally_engaged_achieving_good_results',
        'q3_confidant_dificult_understanding_and_solving_the_problem',
        'q3_confidant_was_it_obvious_what_to_do',
        'q3_confidant_count_unclear_questions',
        'q3_confidant_unclear_questions_description',
        'q3_confidant_technical_issues',
        'q3_confidant_technical_issues_details'
    ]

    def is_displayed(self):
        if self.player.participant.vars.get('is_positive_confidant', False) or self.player.participant.vars.get(
                'is_negative_confidant', False):
            return True

        return False


class PlaceboQ3(Page):

    form_model = models.Player
    form_fields = [

        'q3_second_game_results_surprised',
        'q3_second_game_results_satisfied',
        'q3_second_game_results_upset',
        'q3_second_game_teamwork',
        'q3_second_game_teamspirit',
        'q3_communication_inputs_maxresources_how_useful',
        'q3_followed_communication_inputs',
        'q3_took_advantage_communication_inputs',
        'q3_majority_followed_communication_inputs',
        'q3_majority_took_advantage_communication_inputs',
        'q3_minority_followed_communication_inputs',
        'q3_minority_took_advantage_communication_inputs',
        'q3_how_max_resources_communication_inputs_if_followed',
        'q3_after_second_round_like_others',
        'q3_second_round_impressions',
        'q3_best_strategy_to_max_resources',
        'q3_gender',
        'q3_birthday',
        'q3_main_subject_in_university',
        'q3_already_take_part_in_a_problem_solving',
        'q3_already_took_part_x_times_for_x_months',
        'q3_experiment_itself_was_interessting',
        'q3_were_you_personally_engaged_achieving_good_results',
        'q3_dificult_understanding_and_solving_the_problem',
        'q3_was_it_obvious_what_to_do',
        'q3_count_unclear_questions',
        'q3_unclear_questions_description',
        'q3_technical_issues',
        'q3_technical_issues_details',
        'q3_opinion_about_questions_and_hypotheses'
    ]

    def is_displayed(self):
        if self.player.participant.vars.get('is_positive_confidant', False) or self.player.participant.vars.get(
                'is_negative_confidant', False):
            return False

        return True


page_sequence = [
    ConfidantQ3, PlaceboQ3
]

toilet_questionnaire_3/templates/toilet_questionnaire_3/ConfidantQ3.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags i18n %}

{% block title %}
Fragenbogen 3 für Konfident
{% endblock %}


{% block scripts %}

<!--
<script src="{% static 'global/bootstrap-datepicker-master/js/bootstrap-datepicker.min.js' %}"></script>
<script>
    //~ $(document).ready(function(){
        $("#id_q3_confidant_birthday").attr("placeholder", "YYYY-MM-DD");
        $("#id_q3_confidant_birthday").prop("readonly", true);

        $("#id_q3_confidant_birthday").datepicker({format: "yyyy-mm-dd", autoclose: true});


        $("#id_q3_confidant_birthday").parent().find("span.btn").click(function(){
            $("#id_q3_confidant_birthday").datepicker("show")
        });



    //~ });





</script>

-->
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'global/bootstrap-datepicker-master/css/bootstrap-datepicker3.min.css' %}">
<style>
    #id_q3_birthday {
        background-color: #ffffff;
        cursor: pointer;

    }

    ul.questions input.form-control {
        display: inline;
        margin: 3px;
    }

    ul.questions div.strong {
        font-weight: bold;
    }

    ul.questions div.no-strong *{
        font-weight: normal;
    }

    ul.questions li.question {
        margin-bottom: 40px;
    }

    ul.questions .indent {
        margin-left: 40px;
    }

    ul.questions textarea {
        width: 100%;
        max-width: 100%;
        resize: none;
    }

    ul.questions div.small-tarea textarea {
        height: 50px;
    }

    ul {
     list-style-type: none;
    }

    .indent {

      margin-top : 15px;
    }

</style>
{% endblock %}

{% block content %}
<div class="row">
    <br>
    <div class="col-md-12">
        <ul class="questions">
            <li class="question">
                <div class="strong">Wie stark finden Sie, dass die Gruppenmitglieder im zweiten Spiel
                    zusammenarbeiteten?
                </div>
                <div>Die Gruppenmitglieder arbeiten…</div>
                <ul>
                    <li>überhaupt nicht {{form.q3_confidant_second_game_teamwork}} vollkommen zusammen</li>
                </ul>
            </li>

            <li class="question">
                <div class="strong">Inwiefern empfinden Sie eine Art 'Teamgeist' in der Gruppe?</div>
                <div>Ich empfinde...</div>
                <ul>
                    <li>überhaupt kein {{form.q3_confidant_second_game_teamspirit}} einen starken Teamgeist</li>
                </ul>
            </li>

            <li class="question">
                <div class="strong">In wie weit haben sich die anderen Gruppenmitglieder an die Handlungsempfehlungen
                    gehalten?
                </div>
                <div>Die Mehrheit / die Hälfte der anderen Gruppenmitglieder haben die Handlungsempfehlungen...</div>
                <ul>
                    <li>überhaupt nicht {{form.q3_confidant_majority_followed_communication_inputs}} vollkommen
                        befolgt.
                    </li>
                    <li>überhaupt nicht {{form.q3_confidant_majority_took_advantage_communication_inputs}} maximal
                        ausgenutzt.
                    </li>
                </ul>
                <br>
                <div>Eine Minderheit / die andere Hälfte der anderen Gruppenmitglieder haben die
                    Handlungsempfehlungen...
                </div>
                <ul>
                    <li>überhaupt nicht {{form.q3_confidant_minority_followed_communication_inputs}} vollkommen
                        befolgt.
                    </li>
                    <li>überhaupt nicht {{form.q3_confidant_minority_took_advantage_communication_inputs}} maximal
                        ausgenutzt.
                    </li>
                </ul>
            </li>

            <li class="question">
                <div class="strong">Aufgrund Ihrer Erfahrungen aus den zwei Spielen, was denken Sie nun, wäre die
                    optimale Strategie um die Ressourcen aller zu maximieren?
                </div>
                <div class="indent">{{form.q3_confidant_best_strategy_to_max_resources}}</div>
            </li>

            <br>
            <h4>Angaben zu Ihrer Person</h4>
            <br>
            <ul class="questions">
                <li class="question">
                    <div class="strong">Geschlecht</div>
                    <div class="indent">{{form.q3_confidant_gender}}</div>
                </li>
                <li class="question">
                    <div class="strong">Geburtsjahr:</div>
                    <!-- <div class="indent input-group"> -->
                        <div class="indent small-tared">{{form.q3_confidant_birthday}}</div>
                <!-- <span class="btn input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                -->
                </li>
                <li class="question">
                    <div class="strong">Hauptfach:</div>
                    <div class="indent small-tarea">{{form.q3_confidant_main_subject_in_university}}</div>
                </li>
                <li class="question">
                    <div class="strong">Haben Sie schon einmal in einem Problemlöse-/Kooperations-Experiment wie diesem
                        teilgenommen?
                    </div>
                    <div class="indent">{{form.q3_confidant_already_take_part_in_a_problem_solving}}</div>
                    <br>
                    <div class="strong">Falls Ja, wieviele Male und das letzte Mal vor wievielen Monaten?</div>
                    <div class="indent small-tarea">{{form.q3_confidant_already_took_part_x_times_for_x_months}}</div>
                </li>
            </ul>

            <br>
            <h4>Evaluation des Experiments</h4>
            <br>
            <ul class="questions">
                <li class="question">
                    <div class="strong">Wie interessant war das Experiment für Sie?</div>
                    <ul>
                        <li>überhaupt nicht {{form.q3_confidant_experiment_itself_was_interessting}} äusserst
                            interessant.
                        </li>
                    </ul>
                </li>

                <li class="question">
                    <div class="strong">Wie sehr bemühten Sie sich um möglichst gute Resultate?</div>
                    <ul>
                        <li>überhaupt nicht {{form.q3_confidant_were_you_personally_engaged_achieving_good_results}}
                            äusserst
                            bemüht.
                        </li>
                    </ul>
                </li>

                <li class="question">
                    <div class="strong">Wie schwierig war es, das Problem zu verstehen und zu lösen?</div>
                    <ul>
                        <li>überhaupt nicht {{form.q3_confidant_dificult_understanding_and_solving_the_problem}}
                            äusserst
                            schwierig.
                        </li>
                    </ul>
                </li>

                <li class="question">
                    <div class="strong">Wie klar waren die Anweisungen des Experiments, damit Sie wussten, was Sie im
                        Rahmen des Experiments zu tun haben?
                    </div>
                    <ul>
                        <li>überhaupt nicht {{form.q3_confidant_was_it_obvious_what_to_do}}  äusserst klar.</li>
                    </ul>
                </li>


                <li class="question">
                    <div class="strong">Gab es in den Fragebögen Fragen oder Antwortoptionen, welche unklar waren oder
                        wo Sie unsicher waren, was wir wissen wollen? Wenn ja, wie viele solcher Fragen / Antworten gab
                        es ungefähr (wenn keine, tragen Sie '0' ein)?
                    </div>
                    <div class="indent">{{form.q3_confidant_count_unclear_questions}}</div>
                </li>

                <li class="question">
                    <div class="strong">Erinnern Sie sich noch an Beispiele solcher unklaren Fragen oder
                        Antwortoptionen? Wenn ja, beschreiben Sie kurz, welche diese waren.
                    </div>
                    <div class="indent">{{form.q3_confidant_unclear_questions_description}}</div>
                </li>


                <li class="question">
                    <div class="strong">Traten während den Spielen oder der Kommunikation technische Probleme auf?</div>
                    <br>
                    <ul>
                        <li>{{form.q3_confidant_technical_issues}}</li>
                    </ul>
                </li>

                <li class="question">
                    <div class="strong">Wenn ja, eschreiben Sie kurz die aufgetretenen Probleme:</div>
                    <div class="indent">{{form.q3_confidant_technical_issues_details}}</div>
                </li>

            </ul>
        </ul>
    </div>
</div>

<hr>
<div class="row">
    <div class="col-md-12">
        <span class="pull-right">{% next_button %}</span>
    </div>
</div>

{% endblock %}

toilet_questionnaire_3/templates/toilet_questionnaire_3/Questionnaire3.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags i18n %}

{% block title %}
    {% trans "Questionnaire 3" %}
{% endblock %}


{% block scripts %}
<script src="{% static 'global/bootstrap-datepicker-master/js/bootstrap-datepicker.min.js' %}"></script>
<script>
    //~ $(document).ready(function(){
        $("#id_q3_birthday").attr("placeholder", "YYYY-MM-DD");
        $("#id_q3_birthday").prop("readonly", true);

        $("#id_q3_birthday").datepicker({format: "yyyy-mm-dd", autoclose: true});


        $("#id_q3_birthday").parent().find("span.btn").click(function(){
            $("#id_q3_birthday").datepicker("show")
        });



    //~ });
</script>
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'global/bootstrap-datepicker-master/css/bootstrap-datepicker3.min.css' %}">
<style>
    #id_q3_birthday {
        background-color: #ffffff;
        cursor: pointer;

    }

    ul.questions input.form-control {
        display: inline;
        margin: 3px;
    }

    ul.questions div.strong {
        font-weight: bold;
    }

    ul.questions div.no-strong *{
        font-weight: normal;
    }

    ul.questions li.question {
        margin-bottom: 20px;
    }

    ul.questions .indent {
        margin-left: 40px;
    }

    ul.questions textarea {
        width: 100%;
        max-width: 100%;
        resize: none;
    }

    ul.questions div.small-tarea textarea {
        height: 50px;
    }

    ul.questions li.question ul {
        list-style-type: none;
    }
</style>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
    <ul class="questions">
        <li class="question">
            <div class="strong">{% trans "Evaluating the second game," %}</div>
            <div class="strong">{% trans "I am..." %}</div>
            <ul>
                <li>{% trans "Not at all" %} {{form.q3_second_game_surprised}} {% trans "Entirely surprised" %}</li>
                <li>{% trans "Not at all" %} {{form.q3_second_game_satisfied}}  {% trans "Entirely satisfied" %}</li>
                <li>{% trans "Not at all" %} {{form.q3_second_game_upset}}  {% trans "Entirely upset" %}</li>
            </ul>
        </li>
        <li class="question">
            <div class="strong">{% trans "How much did the players help each other in the second game?" %}</div>
            <div class="strong">{% trans "Group members ..." %}</div>
            <div class="indent">{% trans "Not at all" %} {{form.q3_help_each_other_in_the_second_game}} {% trans "Full cooperation" %}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Is there any 'team spirit' or 'cohesion'?" %}</div>
            <div class="indent">{% trans "Not at all" %} {{form.q3_team_spirit}} {% trans "Entirely" %}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "How important were the recommendations of actions to maximize everyone's resources?" %}</div>
            <div class="indent">{% trans "Not at all" %} {{form.q3_recommendations_of_actions_to_maximize_everyones_resources}} {% trans "Very helpful" %}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Did you follow the recommendations of action?" %}</div>
            <div class="strong">{% trans "The recommendations of actions were..." %}</div>
            <div class="indent">{% trans "Not at all" %} {{form.q3_i_follow_recommendations_of_action_followed}} {% trans "Entirely followed" %}</div>
            <div class="indent">{% trans "Not at all" %} {{form.q3_i_follow_recommendations_of_action_my_advantage}} {% trans "Followed to try to maximize my advantage" %}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Did other members follow the recommendations of action?" %}</div>
            <div class="strong">{% trans "Some or all followed..." %}</div>
            <div class="indent">{% trans "Not at all" %} {{form.q3_others_follow_recommendations_of_action_followed}} {% trans "Entirely" %}</div>
            <div class="indent">{% trans "Not at all" %} {{form.q3_others_follow_recommendations_of_action_their_advantage}} {% trans "Followed to try to maximizing their advantage" %}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Your opinion: If everyone followed the recommendations entirely, would everyone maximize his own resources?" %}</div>
            <div class="indent">{% trans "Not at all" %} {{form.q3_yopinion_if_they_followed_would_everyone_max_his_resources}} {% trans "Entirely" %}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Explain in a few sentences: What was the second game like? What was different and is it (if different) because of the communication? Communicated before, what worked and what didn't work at all? Did you follow the 'rules' and why not? Etc." %}</div>
            <div class="indent">{{form.q3_second_game_different_and_is_it_because_of_the_communication}}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Experienced from the second game and the communication: What would be the best strategy to optimize everyone's resources?" %}</div>
            <div class="indent">{{form.q3_the_best_strategy_to_optimize_everyones_resources}}</div>
        </li>
    </ul>

    <h4>{% trans "Details regarding you as a person" %}</h4>
    <ul class="questions">
        <li class="question">
            <div class="strong">{% trans "Gender" %}</div>
            <div class="indent">{{form.q3_gender}}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Birthday" %}</div>
            <div class="indent input-group">
                {{form.q3_birthday}}
                <span class="btn input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Main subject in university:" %}</div>
            <div class="indent small-tarea">{{form.q3_main_subject_in_university}}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Did you already take part in a problem solving or cooperational game/experiment?" %}</div>
            <div class="indent">{{form.q3_already_take_part_in_a_problem_solving}}</div>
        </li>
    </ul>

    <h4>{% trans "Evaluation" %}</h4>
    <ul class="questions">
        <li class="question">
            <div class="strong">{% trans "The experiment itself was interesting?" %}</div>
            <div class="indent">{% trans "Not at all" %} {{form.q3_experiment_itself_was_interessting}} {% trans "Very interesting" %}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Were you personally engaged achieving good results?" %}</div>
            <div class="indent">{% trans "Not at all" %} {{form.q3_were_you_personally_engaged_achieving_good_results}} {% trans "Entirely" %}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Was it difficult understanding and solving the problem?" %}</div>
            <div class="indent">{% trans "Not at all" %} {{form.q3_dificult_understanding_and_solving_the_problem}} {% trans "Very difficult" %}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Was it obvious what to do?" %}</div>
            <div class="indent">{% trans "Not at all" %} {{form.q3_was_it_obvious_what_to_do}} {% trans "Entirely" %}</div>
        </li>
        <li class="question">
            <div class="strong">{% trans "Please write a short feedback: What was good and what were you upset about? What are possible things to improve/change?" %}</div>
            <div class="indent">{{form.q3_short_feedback}}</div>
        </li>

    </ul>

    </div>
</div>

<hr>
<div class="row">
    <div class="col-md-12">
        <span class="pull-right">{% next_button %}</span>
    </div>
</div>

{% endblock %}